# CPD Logging Fields Configuration
# 
# Instructions:
# - To ENABLE a field for your CPD logging, simply remove the '#' at the beginning of the line.
# - To DISABLE a field, add a '#' at the beginning of the line.
# - "Risk Management" and "Business & Management" are always required and not listed here.
#
# Default enabled:
Mechatronics Engineering

# Available Fields (uncomment to enable):
# Biomedical Engineering
# Chemical Engineering
# Civil Engineering
# Construction Engineering
# Electrical Engineering
# Environmental Engineering
# Information, Telecommunications and Electronic Engineering
# Leadership & Management
# Mechanical Engineering
# Structural Engineering
# Aerospace Engineering
# Building Services Engineering
# Naval Architecture
# Pressure Equipment Design Verification
# Fire Safety Engineering
# Amusement Ride and Devices
# Geotechnical Engineering
# Systems Engineering
# Oil and Gas Pipeline Engineering
# Heritage and Conservation Engineering
# Petroleum Engineering
# Cost Engineering
# Risk Engineering
# Asset Management
# Project Management
# Subsea Engineering
# Cyber Engineering
